// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BoardsStatTable: typeof import('./components/workerDetail/BoardsStatTable.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    EventStatTable: typeof import('./components/workerDetail/EventStatTable.vue')['default']
    FarmDetail: typeof import('./components/FarmDetail.vue')['default']
    MasterStatTable: typeof import('./components/workerDetail/MasterStatTable.vue')['default']
    PoolStatTable: typeof import('./components/workerDetail/PoolStatTable.vue')['default']
    SpiBusStatTable: typeof import('./components/workerDetail/SpiBusStatTable.vue')['default']
    WorkerDetail: typeof import('./components/WorkerDetail.vue')['default']
  }
}

export { }
